import localFont from "next/font/local";
import "./globals.css";
import Footerand from "./components/Footerand";
import Navbar from "./components/Navbar";
import Header from "./components/Header";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });


const monasans = localFont({
  src: "./fonts/MonaSans-Regular.woff2",
  variable: "--font-monaregular",
  // weight: "100 900",
});

const monasansmed = localFont({
  src: "./fonts/MonaSans-Medium.woff2",
  variable: "--font-monamedium",
  // weight: "100 900",
});
const monasansbold = localFont({
  src: "./fonts/MonaSans-Bold.woff2",
  variable: "--font-monabold",
  // weight: "100 900",
});

const monaexpanded = localFont({
  src: "./fonts/MonaSansExpanded-Regular.woff2",
  variable: "--font-monaExpanded",
  // weight: "100 900",
});
const monaexpandedbold = localFont({
  src: "./fonts/MonaSansExpanded-Bold.woff2",
  variable: "--font-monaExpandedbold",
  // weight: "100 900",
});
const monaexpandedextrasbold = localFont({
  src: "./fonts/MonaSansExpanded-ExtraBold.ttf",
  variable: "--font-monaExpandedextrabold",
  // weight: "100 900",
});

const monaexpandedblack = localFont({
  src: "./fonts/MonaSansExpanded-Black.woff2",
  variable: "--font-monaExpandedblack",
  // weight: "100 900",
});
const monacondensedreg= localFont({
  src: "./fonts/MonaSansCondensed-Regular.woff2",
  variable: "--font-monaCondensed",
  // weight: "100 700 900",
});
const monacondensedmed= localFont({
  src: "./fonts/MonaSansCondensed-Medium.woff2",
  variable: "--font-monaCondensedmed",
  // weight: "100 700 900",
});
const monacondensedmeditalic= localFont({
  src: "./fonts/MonaSansCondensed-MediumItalic.woff2",
  variable: "--font-monaCondensedmeditalic",
  // weight: "100 700 900",
});
const monacondensedsemibold= localFont({
  src: "./fonts/MonaSansCondensed-SemiBold.woff2",
  variable: "--font-monaCondensedsemibold",
  // weight: "100 700 900",
});
const monacondensedbold= localFont({
  src: "./fonts/MonaSansCondensed-Bold.woff2",
  variable: "--font-monaCondensedbold",
  // weight: "100 700 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body
        className={`${monasans.variable} ${monasansmed.variable} ${monasansbold.variable} ${monaexpanded.variable} ${monacondensedreg.variable} ${monacondensedmed.variable} ${monacondensedmeditalic.variable} ${monacondensedsemibold.variable} ${monacondensedbold.variable}  ${monaexpandedbold.variable} ${monaexpandedextrasbold.variable} ${monaexpandedblack.variable} font-monaExpanded antialiased font-[130] leading-[1.2] !text-[var(--black)] bg-[var(--black)]`}
      >
         <main  className='bg-[#0e0e0e] min-h-[100vh-133px] '>
         <section>
         <div>
         {/* <Header/> */}
         <Navbar/>
        {children}
      </div>
        {/* <Footerand/> */}
      </section>
      </main>
      </body>
    </html>
  );
}
